#!/bin/sh

# Simple DynDNS Host update script 
# (C) by Paul C. Buetow 2006, 2014
# Mail:  paul at buetow dot org

host=$1
type=$2
addr=$3
timeout=$4

keyname=`echo $host | sed 's/\./-/g; s/-$/./'`

cat << NSUPDATE | tee /var/log/lastnsupdate.log | nsupdate -k $HOME/:$keyname
update delete $host $type
update add $host $timeout IN $type $addr
send
NSUPDATE
